services:
  nimbus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # make sure this directory has the same ownership as the nimbus user from the Dockerfile
      # otherwise Nimbus will not be able to store configs for accounts
      # e.q. mkdir ./nimbus-storage; sudo chown 911:911 ./nimbus-storage
      - './nimbus-storage:/nimbus/data'
    ports:
      - 5314:5314
